### ISSUE TITLE
hii can you please guide me how to add glasses filter 

### ISSUE THREAD

**Issue by saad25011** [nuwandda/snapchat-filter-3d#1]
hii Can you please guide me how to add glasses filter on your code I tried so many time and use blender but nothing works can you explain me in steps how I add it

**Comment by nuwandda** [comment]
Hi. First, you should download a 3D model with a few polygons. This makes your app fast. Using too many polygons makes your app slower. After downloading the model, you can scale down or up and update the object's position according to your face. By position, I mean the (x, y, z) coordinates. Also, please use **.obj** files. Blender modifications need to be done manually.

**Comment by saad25011** [comment]
Hi can you please guide me how to scale our object position because I successfully loaded my glasses but it is not aline with my face coordinates can you please guide me how to Aline it with my eyes

**Comment by saad25011** [comment]
hoi Sad here sir can you please guide me how does you align your cap in
your project I am constantly working to align glasses on my eye but nothing
works can you please guide me
